### ISSUE TITLE
Gesamtkonzept erstellen

### ISSUE THREAD

**Issue by jamadir** [jamadir/Komplexlabor#8]
Funktionsstruktur

**Comment by wangerfel** [comment]
![Funktionsstruktur](https://user-images.githubusercontent.com/114170815/191928555-62944a22-48e4-40b9-aa47-8619344aa730.png)

**Comment by jamadir** [comment]
Mit Github desktop kannst du einen Ordner erstellen der per commit (mit kommentar) und push ins repository geladen wird
https://desktop.github.com

Repository aus dem internet in den Ordner klonen
Danach Änderungen in dem Ordner durchführen
Github desktop öffnen:
![image](https://user-images.githubusercontent.com/34141368/192094777-06372b6e-e2ce-4140-8feb-9c164400a2fd.png)
Dann Push origin:
![image](https://user-images.githubusercontent.com/34141368/192094797-11230019-63eb-4220-83dd-e61321d6b333.png)

Wenn der Arbeitspunkt abgeschlossen ist kann das Issue geschlossen werden:
![image](https://user-images.githubusercontent.com/34141368/192094812-82e2b5f7-d375-4620-93b3-532d07f13220.png)

**Comment by jamadir** [comment]
![image](https://user-images.githubusercontent.com/34141368/192094885-332cc40b-5166-4980-8f23-f93cccb9c046.png)

Jetzt sieht man unter "Milestones" den projektfortschritt
